name: CI

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    name: "Install deps"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Cache node_modules"
        uses: actions/cache@v4
        with:
          path: ./Todo-List-nodejs/node_modules
          key: node_modules-${{ hashFiles('Todo-List-nodejs/package-lock.json') }}

      - name: Setup node to last version
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: "Install deps"
        working-directory: ./Todo-List-nodejs
        run: npm ci

  build:
    needs: ["prepare"]
    name: "Build project"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Restore node_modules
        uses: actions/cache/restore@v4
        with:
          path: ./Todo-List-nodejs/node_modules
          key: node_modules-${{ hashFiles('Todo-List-nodejs/package-lock.json') }}
      - run: ls
      - name: "Build"
        working-directory: ./Todo-List-nodejs
        run: echo "Project built"

  test_jest:
    needs: ["build"]
    name: "Test project"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Test"
        working-directory: ./Todo-List-nodejs
        run: npm run test
        continue-on-error: true
 
  notify:
    needs: ["test_jest"]
    name: "Notify author"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Notify"
        run: |
          env
          echo "CI OK"
