name: CI

on:
  push: ~

jobs:
  prepare:
    name: "Prepare environment"
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.set_version.outputs.version }}
    steps:
      - name: Set up environment
        run: echo "Setup complete"

      - name: Generate build version
        id: set_version
        run: echo "version=1.0.0" >> $GITHUB_ENV

      - name: Set output
        id: set_output
        run: echo "BUILD_VERSION=1.0.0" >> $GITHUB_ENV

  build:
    needs: prepare
    name: "Build project"
    runs-on: ubuntu-latest
    steps:
      - name: Use build version
        run: echo "Building version ${{ needs.prepare.outputs.build_version }}"
